"""add decoded_contents table

Revision ID: 2807b52207ef
Revises: cda6773e5d1f
Create Date: 2026-08-18 22:02:06.344905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2807b52207ef'
down_revision: Union[str, Sequence[str], None] = 'cda6773e5d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decoded_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_decoded_contents_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decoded_contents')),
    sa.UniqueConstraint('paper_id', 'section', 'schema_version', 'prompt_version', name='uq_decoded_contents_paper_section_versions')
    )
    op.create_index(op.f('ix_decoded_contents_paper_id'), 'decoded_contents', ['paper_id'], unique=False)
    op.create_index('ix_decoded_contents_section', 'decoded_contents', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decoded_contents_section', table_name='decoded_contents')
    op.drop_index(op.f('ix_decoded_contents_paper_id'), table_name='decoded_contents')
    op.drop_table('decoded_contents')
    # ### end Alembic commands ###
