"""add institutions, author disambiguation, follows

Revision ID: 2b63c7021702
Revises: 325c35e2d50b
Create Date: 2026-08-31 14:28:32.538377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b63c7021702'
down_revision: Union[str, Sequence[str], None] = '325c35e2d50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('institution_type', sa.String(length=50), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('author_count', sa.Integer(), nullable=False),
    sa.Column('total_citations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_openalex_id'), 'institutions', ['openalex_id'], unique=True)
    op.create_index('ix_institutions_paper_count', 'institutions', ['paper_count'], unique=False)
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_follows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_follows_user_target')
    )
    op.create_index('ix_follows_target', 'follows', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_follows_user_id'), 'follows', ['user_id'], unique=False)
    op.add_column('authors', sa.Column('normalized_name', sa.String(length=300), nullable=False))
    op.add_column('authors', sa.Column('slug', sa.String(length=160), nullable=False))
    op.add_column('authors', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('authors', sa.Column('total_citations', sa.Integer(), nullable=False))
    op.add_column('authors', sa.Column('paper_count', sa.Integer(), nullable=False))
    op.add_column('authors', sa.Column('is_disambiguated', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('uq_authors_openalex_id'), 'authors', type_='unique')
    op.create_index(op.f('ix_authors_institution_id'), 'authors', ['institution_id'], unique=False)
    op.create_index(op.f('ix_authors_normalized_name'), 'authors', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_authors_openalex_id'), 'authors', ['openalex_id'], unique=True)
    op.create_index('ix_authors_paper_count', 'authors', ['paper_count'], unique=False)
    op.create_index(op.f('ix_authors_slug'), 'authors', ['slug'], unique=True)
    op.create_foreign_key(op.f('fk_authors_institution_id_institutions'), 'authors', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_authors_institution_id_institutions'), 'authors', type_='foreignkey')
    op.drop_index(op.f('ix_authors_slug'), table_name='authors')
    op.drop_index('ix_authors_paper_count', table_name='authors')
    op.drop_index(op.f('ix_authors_openalex_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_normalized_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_institution_id'), table_name='authors')
    op.create_unique_constraint(op.f('uq_authors_openalex_id'), 'authors', ['openalex_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('authors', 'is_disambiguated')
    op.drop_column('authors', 'paper_count')
    op.drop_column('authors', 'total_citations')
    op.drop_column('authors', 'institution_id')
    op.drop_column('authors', 'slug')
    op.drop_column('authors', 'normalized_name')
    op.drop_index(op.f('ix_follows_user_id'), table_name='follows')
    op.drop_index('ix_follows_target', table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.drop_index('ix_institutions_paper_count', table_name='institutions')
    op.drop_index(op.f('ix_institutions_openalex_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
