"""add digests and digest preferences

Revision ID: 3218f3537d59
Revises: 2b63c7021702
Create Date: 2026-08-31 13:33:31.132488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3218f3537d59'
down_revision: Union[str, Sequence[str], None] = '2b63c7021702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_papers', sa.Integer(), nullable=False),
    sa.Column('include_general', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_digest_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digest_preferences'))
    )
    op.create_index(op.f('ix_digest_preferences_unsubscribe_token'), 'digest_preferences', ['unsubscribe_token'], unique=True)
    op.create_index(op.f('ix_digest_preferences_user_id'), 'digest_preferences', ['user_id'], unique=True)
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='digest_status'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_digests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digests')),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_digests_user_week')
    )
    op.create_index(op.f('ix_digests_provider_message_id'), 'digests', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_digests_status'), 'digests', ['status'], unique=False)
    op.create_index('ix_digests_status_week', 'digests', ['status', 'week_start'], unique=False)
    op.create_index(op.f('ix_digests_user_id'), 'digests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digests_user_id'), table_name='digests')
    op.drop_index('ix_digests_status_week', table_name='digests')
    op.drop_index(op.f('ix_digests_status'), table_name='digests')
    op.drop_index(op.f('ix_digests_provider_message_id'), table_name='digests')
    op.drop_table('digests')
    op.drop_index(op.f('ix_digest_preferences_user_id'), table_name='digest_preferences')
    op.drop_index(op.f('ix_digest_preferences_unsubscribe_token'), table_name='digest_preferences')
    op.drop_table('digest_preferences')
    # ### end Alembic commands ###
