"""add topic snapshots and clustering runs

Revision ID: 325c35e2d50b
Revises: a7b89b87874a
Create Date: 2026-08-29 16:01:10.194696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325c35e2d50b'
down_revision: Union[str, Sequence[str], None] = 'a7b89b87874a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('papers_clustered', sa.Integer(), nullable=False),
    sa.Column('topics_found', sa.Integer(), nullable=False),
    sa.Column('outliers', sa.Integer(), nullable=False),
    sa.Column('min_cluster_size', sa.Integer(), nullable=False),
    sa.Column('naming_cost_usd', sa.Float(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clustering_runs'))
    )
    op.create_table('topic_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('total_citations', sa.Integer(), nullable=False),
    sa.Column('mean_priority', sa.Float(), nullable=False),
    sa.Column('hn_mentions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_snapshots_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_snapshots')),
    sa.UniqueConstraint('topic_id', 'window_start', name='uq_topic_snapshots_topic_window')
    )
    op.create_index(op.f('ix_topic_snapshots_topic_id'), 'topic_snapshots', ['topic_id'], unique=False)
    op.create_index('ix_topic_snapshots_window', 'topic_snapshots', ['window_start'], unique=False)
    op.add_column('topics', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('topics', sa.Column('paper_count', sa.Integer(), nullable=False))
    op.add_column('topics', sa.Column('last_clustered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('topics', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_topics_cluster_id'), 'topics', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_topics_is_active'), 'topics', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_is_active'), table_name='topics')
    op.drop_index(op.f('ix_topics_cluster_id'), table_name='topics')
    op.drop_column('topics', 'is_active')
    op.drop_column('topics', 'last_clustered_at')
    op.drop_column('topics', 'paper_count')
    op.drop_column('topics', 'keywords')
    op.drop_column('topics', 'cluster_id')
    op.drop_index('ix_topic_snapshots_window', table_name='topic_snapshots')
    op.drop_index(op.f('ix_topic_snapshots_topic_id'), table_name='topic_snapshots')
    op.drop_table('topic_snapshots')
    op.drop_table('clustering_runs')
    # ### end Alembic commands ###
