"""add podcasts table

Revision ID: 612ddac4a529
Revises: 3218f3537d59
Create Date: 2026-09-01 18:12:53.977598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612ddac4a529'
down_revision: Union[str, Sequence[str], None] = '3218f3537d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCRIPTED', 'GENERATING_AUDIO', 'READY', 'FAILED', name='podcast_status'), nullable=False),
    sa.Column('script', sa.JSON(), nullable=True),
    sa.Column('script_model', sa.String(length=100), nullable=True),
    sa.Column('script_cost_usd', sa.Float(), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('audio_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('audio_cost_usd', sa.Float(), nullable=False),
    sa.Column('chapters', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_podcasts_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcasts')),
    sa.UniqueConstraint('paper_id', 'schema_version', 'prompt_version', name='uq_podcasts_paper_versions')
    )
    op.create_index(op.f('ix_podcasts_paper_id'), 'podcasts', ['paper_id'], unique=False)
    op.create_index('ix_podcasts_status', 'podcasts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_podcasts_status', table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_paper_id'), table_name='podcasts')
    op.drop_table('podcasts')
    # ### end Alembic commands ###
