"""add explanation_modes and credit_ledger

Revision ID: a7b89b87874a
Revises: a277bb9c2941
Create Date: 2026-08-26 22:30:19.319746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b89b87874a'
down_revision: Union[str, Sequence[str], None] = 'a277bb9c2941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=30), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_credit_ledger_paper_id_papers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_ledger_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger'))
    )
    op.create_index('ix_credit_ledger_user_created', 'credit_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('explanation_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', 'NOT_APPLICABLE', name='mode_status'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_explanation_modes_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_explanation_modes_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explanation_modes')),
    sa.UniqueConstraint('paper_id', 'mode', 'schema_version', 'prompt_version', name='uq_explanation_modes_paper_mode_versions')
    )
    op.create_index(op.f('ix_explanation_modes_paper_id'), 'explanation_modes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_explanation_modes_status'), 'explanation_modes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanation_modes_status'), table_name='explanation_modes')
    op.drop_index(op.f('ix_explanation_modes_paper_id'), table_name='explanation_modes')
    op.drop_table('explanation_modes')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_index('ix_credit_ledger_user_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    # ### end Alembic commands ###
