"""add users, saved_papers, read_events

Revision ID: f63f126db8a5
Revises: 2807b52207ef
Create Date: 2026-08-25 00:05:32.007525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63f126db8a5'
down_revision: Union[str, Sequence[str], None] = '2807b52207ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('credits_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('read_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_read_events_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_read_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_events'))
    )
    op.create_index(op.f('ix_read_events_paper_id'), 'read_events', ['paper_id'], unique=False)
    op.create_index('ix_read_events_user_created', 'read_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_read_events_user_id'), 'read_events', ['user_id'], unique=False)
    op.create_table('saved_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_saved_papers_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_papers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_papers')),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_saved_papers_user_paper')
    )
    op.create_index(op.f('ix_saved_papers_paper_id'), 'saved_papers', ['paper_id'], unique=False)
    op.create_index(op.f('ix_saved_papers_user_id'), 'saved_papers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_papers_user_id'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_paper_id'), table_name='saved_papers')
    op.drop_table('saved_papers')
    op.drop_index(op.f('ix_read_events_user_id'), table_name='read_events')
    op.drop_index('ix_read_events_user_created', table_name='read_events')
    op.drop_index(op.f('ix_read_events_paper_id'), table_name='read_events')
    op.drop_table('read_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
