/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Papers
         * @description Feed principal, ordenado por priority_score. Cacheado por 5 minutos.
         */
        get: operations["list_papers_v1_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/{arxiv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper
         * @description Detalhe completo de um paper, com todo o conteúdo decodificado.
         */
        get: operations["get_paper_v1_papers__arxiv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/sitemap/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sitemap Entries
         * @description Lista enxuta pro sitemap. Papers decodificados marcados, porque
         *     recebem prioridade maior no XML gerado pelo frontend.
         */
        get: operations["sitemap_entries_v1_papers_sitemap_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Busca semântica sobre papers decodificados.
         *
         *     Cacheada por 15 minutos. Um hit economiza dois embeddings da query
         *     (as duas coleções usam modelos diferentes) mais uma chamada ao reranker.
         */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved */
        get: operations["list_saved_v1_me_saved_get"];
        put?: never;
        /**
         * Toggle Save
         * @description Salva ou remove um paper da biblioteca do usuário.
         */
        post: operations["toggle_save_v1_me_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved/{arxiv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Saved */
        get: operations["is_saved_v1_me_saved__arxiv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Read
         * @description Registra que o usuário leu um paper. Alimenta personalização na Semana 5.
         */
        post: operations["record_read_v1_me_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/{arxiv_id}/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Modes
         * @description Lista todos os modos com status. Conteúdo incluído apenas para os prontos.
         *     Funciona sem autenticação — modos em cache são públicos.
         */
        get: operations["list_modes_v1_papers__arxiv_id__modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/{arxiv_id}/modes/{mode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mode
         * @description Busca um modo específico. Só retorna se estiver em cache.
         */
        get: operations["get_mode_v1_papers__arxiv_id__modes__mode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/{arxiv_id}/modes/{mode}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Dispara a geração de um modo. Retorna imediatamente.
         *
         *     Cache hit devolve o conteúdo na hora, de graça.
         *     Caso contrário gasta o crédito, agenda a geração, e devolve
         *     status=generating. O cliente faz polling no GET.
         */
        post: operations["generate_v1_papers__arxiv_id__modes__mode__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Topics
         * @description Todos os tópicos ativos.
         */
        get: operations["list_topics_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topics/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Field Pulse
         * @description Visão geral: o que está subindo, esfriando, emergindo, e o que é maior.
         *
         *     Esta é a home do Field Pulse.
         */
        get: operations["field_pulse_v1_topics_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topic
         * @description Detalhe de um tópico: série temporal, autores, papers.
         */
        get: operations["get_topic_v1_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Authors
         * @description Autores mais ativos no corpus.
         */
        get: operations["list_authors_v1_authors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Author */
        get: operations["get_author_v1_authors__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Institutions */
        get: operations["list_institutions_v1_institutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/institutions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Institution */
        get: operations["get_institution_v1_institutions__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Follows
         * @description Tudo que o usuário segue. Alimenta o digest.
         */
        get: operations["list_follows_v1_follows_get"];
        put?: never;
        /**
         * Toggle Follow
         * @description Segue ou deixa de seguir um autor, instituição ou tópico.
         */
        post: operations["toggle_follow_v1_follows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorCard */
        AuthorCard: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
            /** Paper Count */
            paper_count: number;
            /** Total Citations */
            total_citations: number;
            /**
             * Is Disambiguated
             * @default false
             */
            is_disambiguated: boolean;
        };
        /** AuthorDetail */
        AuthorDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
            /** Institution Slug */
            institution_slug?: string | null;
            /** Paper Count */
            paper_count: number;
            /** Total Citations */
            total_citations: number;
            /** Is Disambiguated */
            is_disambiguated: boolean;
            /** First Paper At */
            first_paper_at?: string | null;
            /** Latest Paper At */
            latest_paper_at?: string | null;
            /** Topics */
            topics?: components["schemas"]["AuthorTopic"][];
            /** Coauthors */
            coauthors?: components["schemas"]["CoAuthor"][];
            /** Papers */
            papers?: components["schemas"]["PaperCard"][];
            /**
             * Is Following
             * @default false
             */
            is_following: boolean;
        };
        /** AuthorOut */
        AuthorOut: {
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
        };
        /** AuthorTopic */
        AuthorTopic: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Paper Count */
            paper_count: number;
        };
        /** CoAuthor */
        CoAuthor: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Shared Papers */
            shared_papers: number;
        };
        /** FeedResponse */
        FeedResponse: {
            /** Papers */
            papers: components["schemas"]["PaperCard"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** FollowRequest */
        FollowRequest: {
            /** Target Type */
            target_type: string;
            /** Slug */
            slug: string;
        };
        /** FollowResponse */
        FollowResponse: {
            /** Target Type */
            target_type: string;
            /** Slug */
            slug: string;
            /** Following */
            following: boolean;
        };
        /** GenerateModeResponse */
        GenerateModeResponse: {
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Cached */
            cached: boolean;
            /** Content */
            content?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Credits Remaining */
            credits_remaining?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Poll After Ms
             * @description Se status=generating, esperar isto antes do próximo GET
             */
            poll_after_ms?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstitutionCard */
        InstitutionCard: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Country Code */
            country_code?: string | null;
            /** Paper Count */
            paper_count: number;
            /** Author Count */
            author_count: number;
            /** Total Citations */
            total_citations: number;
        };
        /** InstitutionDetail */
        InstitutionDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Country Code */
            country_code?: string | null;
            /** Paper Count */
            paper_count: number;
            /** Author Count */
            author_count: number;
            /** Total Citations */
            total_citations: number;
            /** Top Authors */
            top_authors?: components["schemas"]["AuthorCard"][];
            /** Topics */
            topics?: components["schemas"]["AuthorTopic"][];
            /** Papers */
            papers?: components["schemas"]["PaperCard"][];
            /**
             * Is Following
             * @default false
             */
            is_following: boolean;
        };
        /** InstitutionsListResponse */
        InstitutionsListResponse: {
            /** Institutions */
            institutions?: components["schemas"]["InstitutionCard"][];
            /** Total */
            total: number;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string | null;
            /** Display Name */
            display_name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Plan */
            plan: string;
            /** Credits Remaining */
            credits_remaining: number;
            /** Credits Reset At */
            credits_reset_at: string | null;
            /** Saved Count */
            saved_count: number;
        };
        /** ModeInfo */
        ModeInfo: {
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Cached */
            cached: boolean;
            /** Content */
            content?: {
                [key: string]: unknown;
            } | null;
            /** Generated At */
            generated_at?: string | null;
        };
        /** ModesListResponse */
        ModesListResponse: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Modes */
            modes: components["schemas"]["ModeInfo"][];
            /** Credits Remaining */
            credits_remaining?: number | null;
            /** Plan */
            plan?: string | null;
        };
        /**
         * PaperCard
         * @description Versão resumida — usada no feed.
         */
        PaperCard: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /**
             * One Sentence
             * @description Resumo de uma frase, se o paper já foi decodificado
             */
            one_sentence?: string | null;
            /** Authors */
            authors?: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Categories */
            categories?: string[];
            /** Priority Score */
            priority_score: number;
            /** Citation Count */
            citation_count: number;
            /** Hn Mentions */
            hn_mentions: number;
            /** Is Decoded */
            is_decoded: boolean;
            /** Decoded Sections */
            decoded_sections?: string[];
        };
        /**
         * PaperDetail
         * @description Versão completa — usada na página do paper.
         */
        PaperDetail: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors?: components["schemas"]["AuthorOut"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Categories */
            categories?: string[];
            /** Pdf Url */
            pdf_url: string;
            /** Priority Score */
            priority_score: number;
            /** Citation Count */
            citation_count: number;
            /** Hn Mentions */
            hn_mentions: number;
            /** Hn Url */
            hn_url?: string | null;
            /**
             * Decoded
             * @description Mapa de nome_da_seção → conteúdo JSON
             */
            decoded?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Decoded At */
            decoded_at?: string | null;
        };
        /** PeopleListResponse */
        PeopleListResponse: {
            /** Authors */
            authors?: components["schemas"]["AuthorCard"][];
            /** Total */
            total: number;
        };
        /**
         * PulseResponse
         * @description Visão geral do campo — a home do Field Pulse.
         */
        PulseResponse: {
            /** Rising */
            rising?: components["schemas"]["TopicCard"][];
            /** Cooling */
            cooling?: components["schemas"]["TopicCard"][];
            /** Emerging */
            emerging?: components["schemas"]["TopicCard"][];
            /** Largest */
            largest?: components["schemas"]["TopicCard"][];
            /** Total Topics */
            total_topics: number;
            /** Total Papers */
            total_papers: number;
            /** Weeks Covered */
            weeks_covered: number;
            /** Clustered At */
            clustered_at?: string | null;
        };
        /** ReadRequest */
        ReadRequest: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Section */
            section?: string | null;
        };
        /** SavedResponse */
        SavedResponse: {
            /** Papers */
            papers: components["schemas"]["PaperCard"][];
            /** Total */
            total: number;
        };
        /** SearchHit */
        SearchHit: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** One Sentence */
            one_sentence?: string | null;
            /**
             * Snippet
             * @description Trecho do paper que casou com a busca
             */
            snippet?: string | null;
            /**
             * Section
             * @description Seção do paper de onde veio o trecho
             */
            section?: string | null;
            /** Score */
            score: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Total Found */
            total_found: number;
            /** Reranked */
            reranked: boolean;
            /** Latency Ms */
            latency_ms: number;
        };
        /** SitemapEntry */
        SitemapEntry: {
            /** Arxiv Id */
            arxiv_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Decoded */
            is_decoded: boolean;
        };
        /** SitemapResponse */
        SitemapResponse: {
            /** Entries */
            entries: components["schemas"]["SitemapEntry"][];
            /** Total */
            total: number;
        };
        /** ToggleSaveRequest */
        ToggleSaveRequest: {
            /** Arxiv Id */
            arxiv_id: string;
        };
        /** ToggleSaveResponse */
        ToggleSaveResponse: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Saved */
            saved: boolean;
        };
        /** TopicAuthor */
        TopicAuthor: {
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
            /** Paper Count */
            paper_count: number;
            /** Total Citations */
            total_citations: number;
        };
        /**
         * TopicCard
         * @description Versão de listagem.
         */
        TopicCard: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Paper Count */
            paper_count: number;
            /**
             * Recent Papers
             * @description Papers nas últimas 4 semanas
             * @default 0
             */
            recent_papers: number;
            /**
             * Momentum
             * @description Variação relativa vs. as 4 semanas anteriores
             * @default 0
             */
            momentum: number;
            /**
             * Momentum Label
             * @default steady
             */
            momentum_label: string;
        };
        /** TopicDetail */
        TopicDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Paper Count */
            paper_count: number;
            /** Recent Papers */
            recent_papers: number;
            /** Prior Papers */
            prior_papers: number;
            /** Momentum */
            momentum: number;
            /** Momentum Label */
            momentum_label: string;
            /** Timeline */
            timeline?: components["schemas"]["TopicPoint"][];
            /** Top Authors */
            top_authors?: components["schemas"]["TopicAuthor"][];
            /** Papers */
            papers?: components["schemas"]["PaperCard"][];
            /** Last Clustered At */
            last_clustered_at?: string | null;
        };
        /**
         * TopicPoint
         * @description Um ponto na série temporal.
         */
        TopicPoint: {
            /**
             * Week
             * Format: date-time
             */
            week: string;
            /** Papers */
            papers: number;
            /** Citations */
            citations: number;
            /** Mean Priority */
            mean_priority: number;
            /** Hn Mentions */
            hn_mentions: number;
        };
        /** TopicsListResponse */
        TopicsListResponse: {
            /** Topics */
            topics: components["schemas"]["TopicCard"][];
            /** Total */
            total: number;
            /** Clustered At */
            clustered_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_papers_v1_papers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filtra por categoria arXiv */
                category?: string | null;
                /** @description Só papers já decodificados */
                decoded_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_v1_papers__arxiv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sitemap_entries_v1_papers_sitemap_entries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                /** @description Query de busca */
                q: string;
                limit?: number;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_saved_v1_me_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedResponse"];
                };
            };
        };
    };
    toggle_save_v1_me_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    is_saved_v1_me_saved__arxiv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_read_v1_me_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modes_v1_papers__arxiv_id__modes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mode_v1_papers__arxiv_id__modes__mode__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
                mode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_v1_papers__arxiv_id__modes__mode__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
                mode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateModeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_v1_topics_get: {
        parameters: {
            query?: {
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    field_pulse_v1_topics_pulse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseResponse"];
                };
            };
        };
    };
    get_topic_v1_topics__slug__get: {
        parameters: {
            query?: {
                paper_limit?: number;
                weeks?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_authors_v1_authors_get: {
        parameters: {
            query?: {
                limit?: number;
                min_papers?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_author_v1_authors__slug__get: {
        parameters: {
            query?: {
                paper_limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_institutions_v1_institutions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_institution_v1_institutions__slug__get: {
        parameters: {
            query?: {
                paper_limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_follows_v1_follows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowResponse"][];
                };
            };
        };
    };
    toggle_follow_v1_follows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
