/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Papers
         * @description Feed principal, ordenado por priority_score.
         */
        get: operations["list_papers_v1_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/{arxiv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper
         * @description Detalhe completo de um paper, com todo o conteúdo decodificado.
         */
        get: operations["get_paper_v1_papers__arxiv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/sitemap/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sitemap Entries
         * @description Lista enxuta pro sitemap. Papers decodificados primeiro — são os que
         *     têm conteúdo original e valem indexação prioritária.
         */
        get: operations["sitemap_entries_v1_papers_sitemap_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved */
        get: operations["list_saved_v1_me_saved_get"];
        put?: never;
        /**
         * Toggle Save
         * @description Salva ou remove um paper da biblioteca do usuário.
         */
        post: operations["toggle_save_v1_me_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved/{arxiv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Saved */
        get: operations["is_saved_v1_me_saved__arxiv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Read
         * @description Registra que o usuário leu um paper. Alimenta personalização na Semana 5.
         */
        post: operations["record_read_v1_me_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorOut */
        AuthorOut: {
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
        };
        /** FeedResponse */
        FeedResponse: {
            /** Papers */
            papers: components["schemas"]["PaperCard"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string | null;
            /** Display Name */
            display_name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Plan */
            plan: string;
            /** Credits Remaining */
            credits_remaining: number;
            /** Credits Reset At */
            credits_reset_at: string | null;
            /** Saved Count */
            saved_count: number;
        };
        /**
         * PaperCard
         * @description Versão resumida — usada no feed.
         */
        PaperCard: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /**
             * One Sentence
             * @description Resumo de uma frase, se o paper já foi decodificado
             */
            one_sentence?: string | null;
            /** Authors */
            authors?: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Categories */
            categories?: string[];
            /** Priority Score */
            priority_score: number;
            /** Citation Count */
            citation_count: number;
            /** Hn Mentions */
            hn_mentions: number;
            /** Is Decoded */
            is_decoded: boolean;
            /** Decoded Sections */
            decoded_sections?: string[];
        };
        /**
         * PaperDetail
         * @description Versão completa — usada na página do paper.
         */
        PaperDetail: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors?: components["schemas"]["AuthorOut"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Categories */
            categories?: string[];
            /** Pdf Url */
            pdf_url: string;
            /** Priority Score */
            priority_score: number;
            /** Citation Count */
            citation_count: number;
            /** Hn Mentions */
            hn_mentions: number;
            /** Hn Url */
            hn_url?: string | null;
            /**
             * Decoded
             * @description Mapa de nome_da_seção → conteúdo JSON
             */
            decoded?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Decoded At */
            decoded_at?: string | null;
        };
        /** ReadRequest */
        ReadRequest: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Section */
            section?: string | null;
        };
        /** SavedResponse */
        SavedResponse: {
            /** Papers */
            papers: components["schemas"]["PaperCard"][];
            /** Total */
            total: number;
        };
        /** SearchHit */
        SearchHit: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** One Sentence */
            one_sentence?: string | null;
            /**
             * Snippet
             * @description Trecho do paper que casou com a busca
             */
            snippet?: string | null;
            /**
             * Section
             * @description Seção do paper de onde veio o trecho
             */
            section?: string | null;
            /** Score */
            score: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Total Found */
            total_found: number;
            /** Reranked */
            reranked: boolean;
            /** Latency Ms */
            latency_ms: number;
        };
        /** SitemapEntry */
        SitemapEntry: {
            /** Arxiv Id */
            arxiv_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Decoded */
            is_decoded: boolean;
        };
        /** SitemapResponse */
        SitemapResponse: {
            /** Entries */
            entries: components["schemas"]["SitemapEntry"][];
            /** Total */
            total: number;
        };
        /** ToggleSaveRequest */
        ToggleSaveRequest: {
            /** Arxiv Id */
            arxiv_id: string;
        };
        /** ToggleSaveResponse */
        ToggleSaveResponse: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Saved */
            saved: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_papers_v1_papers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filtra por categoria arXiv */
                category?: string | null;
                /** @description Só papers já decodificados */
                decoded_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_v1_papers__arxiv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sitemap_entries_v1_papers_sitemap_entries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                /** @description Query de busca */
                q: string;
                limit?: number;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_saved_v1_me_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedResponse"];
                };
            };
        };
    };
    toggle_save_v1_me_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    is_saved_v1_me_saved__arxiv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_read_v1_me_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
