/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Papers
         * @description Feed principal, ordenado por priority_score.
         */
        get: operations["list_papers_v1_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/papers/{arxiv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper
         * @description Detalhe completo de um paper, com todo o conteúdo decodificado.
         */
        get: operations["get_paper_v1_papers__arxiv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorOut */
        AuthorOut: {
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
        };
        /** FeedResponse */
        FeedResponse: {
            /** Papers */
            papers: components["schemas"]["PaperCard"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PaperCard
         * @description Versão resumida — usada no feed.
         */
        PaperCard: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /**
             * One Sentence
             * @description Resumo de uma frase, se o paper já foi decodificado
             */
            one_sentence?: string | null;
            /** Authors */
            authors?: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Categories */
            categories?: string[];
            /** Priority Score */
            priority_score: number;
            /** Citation Count */
            citation_count: number;
            /** Hn Mentions */
            hn_mentions: number;
            /** Is Decoded */
            is_decoded: boolean;
            /** Decoded Sections */
            decoded_sections?: string[];
        };
        /**
         * PaperDetail
         * @description Versão completa — usada na página do paper.
         */
        PaperDetail: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors?: components["schemas"]["AuthorOut"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Categories */
            categories?: string[];
            /** Pdf Url */
            pdf_url: string;
            /** Priority Score */
            priority_score: number;
            /** Citation Count */
            citation_count: number;
            /** Hn Mentions */
            hn_mentions: number;
            /** Hn Url */
            hn_url?: string | null;
            /**
             * Decoded
             * @description Mapa de nome_da_seção → conteúdo JSON
             */
            decoded?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Decoded At */
            decoded_at?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** One Sentence */
            one_sentence?: string | null;
            /**
             * Snippet
             * @description Trecho do paper que casou com a busca
             */
            snippet?: string | null;
            /**
             * Section
             * @description Seção do paper de onde veio o trecho
             */
            section?: string | null;
            /** Score */
            score: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Total Found */
            total_found: number;
            /** Reranked */
            reranked: boolean;
            /** Latency Ms */
            latency_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_papers_v1_papers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filtra por categoria arXiv */
                category?: string | null;
                /** @description Só papers já decodificados */
                decoded_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_v1_papers__arxiv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                /** @description Query de busca */
                q: string;
                limit?: number;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
